# This is a basic workflow to help you get started with Actions
name: pr_check

# Controls when the workflow will run
on:
  # Triggers the workflow on push events to the "main" branch
  push:
    branches:
      - main
    paths:
      - 'git-PR-check/*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Login to Docker Hub
      - name: Login to Docker Hub
        run: echo ${{secrets.DOCKERHUB_TOKEN}} | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin

      # Build and Push Docker image
      - name: Build and Push
        run: |
          echo "Start Building Image"
          docker build -t jira:latest -f git-PR-check/Dockerfile git-PR-check
          docker tag jira:latest skc1998/jira:v0.0.1
          docker push skc1998/jira:v0.0.1
        env:
          DOCKER_CLI_AGGREGATE: 1
          DOCKER_BUILDKIT: 1
